<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Modules\Account\Entities\AccountUtility;
use Spatie\Permission\Models\Permission;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\userActiveModule;

class AccountantSeeder extends Seeder
{
    public function run()
    {
        // Retrieve or create the admin to set as the `created_by` user
        $admin = User::where('type', 'company')->first();

        // Create or retrieve the junior accountant user
        $user = User::where('type', 'accountant')->first();
        if (empty($user)) {
            $accountant = new User();
            $accountant->name = 'Junior Accountant';
            $accountant->email = 'junior_accountant@daa.com';
            $accountant->email_verified_at = date('Y-m-d H:i:s');
            $accountant->password = Hash::make('1234');
            $accountant->type = 'accountant';
            $accountant->active_status = 1;
            $accountant->active_workspace = 1;
            $accountant->avatar = 'uploads/users-avatar/avatar.png';
            $accountant->requested_plan = 0;
            $accountant->dark_mode = 0;
            $accountant->lang = 'en';
            $accountant->messenger_color = '#2180f3';
            $accountant->workspace_id = 1;
            $accountant->active_plan = 2;
            $accountant->active_module = 'Account,Hrm,Stripe,ProductService,Pos,Taskly,Paypal,Lead,DoubleEntry';
            $accountant->plan_expire_date = '2050-07-25';
            $accountant->is_trial_done = 0;
            $accountant->total_user = -1;
            $accountant->total_workspace = -1;
            $accountant->seeder_run = 0;
            $accountant->is_enable_login = 1;
            $accountant->is_disable = 1;
            $accountant->created_by = $admin->id;
            $accountant->save();
        } else {
            $accountant = $user;
        }

        // Clear cache (to avoid issues with Spatie package caching)
        Artisan::call('cache:clear');

        // Create or retrieve the accountant role
        $role = Role::firstOrCreate(
            ['name' => 'accountant', 'guard_name' => 'web'],
            ['created_by' => 1]
        );

        // Assign the role to the user
        if (!$accountant->hasRole('accountant')) {
            $accountant->assignRole($role);
        }

        // Define permissions for the accountant role
        $permissions = [
            'user manage',
            'user create',
            'user edit',
            'user delete',
            'user profile manage',
            'user chat manage',
            'user reset password',
            'user login manage',
            'user import',
            'user logs history',
            'workspace manage',
            'workspace create',
            'workspace edit',
            'workspace delete',
            'roles manage',
            'roles create',
            'roles edit',
            'roles delete',
            'plan manage',
            'plan purchase',
            'plan subscribe',
            'plan orders',
            'proposal manage',
            'proposal create',
            'proposal edit',
            'proposal delete',
            'proposal show',
            'proposal send',
            'proposal duplicate',
            'proposal product delete',
            'proposal convert invoice',
            'invoice manage',
            'invoice create',
            'invoice edit',
            'invoice delete',
            'invoice show',
            'invoice send',
            'invoice duplicate',
            'invoice product delete',
            'invoice payment create',
            'invoice payment delete',
            'setting manage',
            'setting logo manage',
            'setting theme manage',
            'helpdesk ticket manage',
            'helpdesk ticket create',
            'helpdesk ticket edit',
            'helpdesk ticket show',
            'helpdesk ticket reply',
            'helpdesk ticket delete',
            'account dashboard manage',
            'bank account manage',
            'bank account create',
            'bank account edit',
            'bank account delete',
            'bank transfer manage',
            'bank transfer create',
            'bank transfer edit',
            'bank transfer delete',
            'account manage',
            'customer manage',
            'customer create',
            'customer edit',
            'customer delete',
            'customer show',
            'customer import',
            'vendor manage',
            'vendor create',
            'vendor edit',
            'vendor delete',
            'vendor show',
            'vendor import',
            'creditnote manage',
            'creditnote create',
            'creditnote edit',
            'creditnote delete',
            'revenue manage',
            'revenue create',
            'revenue edit',
            'revenue delete',
            'report manage',
            'bill manage',
            'bill create',
            'bill edit',
            'bill delete',
            'bill payment manage',
            'bill payment create',
            'bill payment edit',
            'bill payment delete',
            'bill show',
            'bill duplicate',
            'bill product delete',
            'bill send',
            'debitnote manage',
            'debitnote create',
            'debitnote edit',
            'debitnote delete',
            'expense payment manage',
            'expense payment create',
            'expense payment edit',
            'expense payment delete',
            'report transaction manage',
            'report statement manage',
            'report income manage',
            'report expense',
            'report income vs expense manage',
            'report tax manage',
            'report loss & profit  manage',
            'report invoice manage',
            'report bill manage',
            'report stock manage',
            'sidebar income manage',
            'sidebar expanse manage',
            'sidebar banking manage',
            'chart of account manage',
            'chart of account create',
            'chart of account edit',
            'chart of account show',
            'chart of account delete',
            'hrm manage',
            'hrm dashboard manage',
            'sidebar hrm report manage',
            'document manage',
            'document create',
            'document edit',
            'document delete',
            'attendance manage',
            'attendance create',
            'attendance edit',
            'attendance delete',
            'attendance import',
            'branch manage',
            'branch create',
            'branch edit',
            'branch delete',
            'department manage',
            'department create',
            'department edit',
            'department delete',
            'designation manage',
            'designation create',
            'designation edit',
            'designation delete',
            'employee manage',
            'employee create',
            'employee edit',
            'employee delete',
            'employee show',
            'employee profile manage',
            'employee profile show',
            'employee import',
            'documenttype manage',
            'documenttype create',
            'documenttype edit',
            'documenttype delete',
            'companypolicy manage',
            'companypolicy create',
            'companypolicy edit',
            'companypolicy delete',
            'leave manage',
            'leave create',
            'leave edit',
            'leave delete',
            'leave approver manage',
            'leavetype manage',
            'leavetype create',
            'leavetype edit',
            'leavetype delete',
            'award manage',
            'award create',
            'award edit',
            'award delete',
            'awardtype manage',
            'awardtype create',
            'awardtype edit',
            'awardtype delete',
            'transfer manage',
            'transfer create',
            'transfer edit',
            'transfer delete',
            'resignation manage',
            'resignation create',
            'resignation edit',
            'resignation delete',
            'travel manage',
            'travel create',
            'travel edit',
            'travel delete',
            'promotion manage',
            'promotion create',
            'promotion edit',
            'promotion delete',
            'complaint manage',
            'complaint create',
            'complaint edit',
            'complaint delete',
            'warning manage',
            'warning create',
            'warning edit',
            'warning delete',
            'termination manage',
            'termination create',
            'termination edit',
            'termination delete',
            'termination description',
            'terminationtype manage',
            'terminationtype create',
            'terminationtype edit',
            'terminationtype delete',
            'announcement manage',
            'announcement create',
            'announcement edit',
            'announcement delete',
            'holiday manage',
            'holiday create',
            'holiday edit',
            'holiday delete',
            'holiday import',
            'attendance report manage',
            'leave report manage',
            'paysliptype manage',
            'paysliptype create',
            'paysliptype edit',
            'paysliptype delete',
            'allowanceoption manage',
            'allowanceoption create',
            'allowanceoption edit',
            'allowanceoption delete',
            'loanoption manage',
            'loanoption create',
            'loanoption edit',
            'loanoption delete',
            'deductionoption manage',
            'deductionoption create',
            'deductionoption edit',
            'deductionoption delete',
            'setsalary manage',
            'setsalary pay slip manage',
            'setsalary create',
            'setsalary edit',
            'setsalary show',
            'allowance manage',
            'allowance create',
            'allowance edit',
            'allowance delete',
            'commission manage',
            'commission create',
            'commission edit',
            'commission delete',
            'loan manage',
            'loan create',
            'loan edit',
            'loan delete',
            'saturation deduction manage',
            'saturation deduction create',
            'saturation deduction edit',
            'saturation deduction delete',
            'other payment manage',
            'other payment create',
            'other payment edit',
            'other payment delete',
            'overtime manage',
            'overtime create',
            'overtime edit',
            'overtime delete',
            'branch name edit',
            'department name edit',
            'designation name edit',
            'event manage',
            'event create',
            'event edit',
            'event delete',
            'sidebar payroll manage',
            'sidebar hr admin  manage',
            'letter joining manage',
            'letter certificate manage',
            'letter noc manage',
            'ip restrict manage',
            'ip restrict create',
            'ip restrict edit',
            'ip restrict delete',
            'doubleentry manage',
            'report ledger',
            'report balance sheet',
            'report profit loss',
            'report trial balance',
            'journalentry manage',
            'journalentry create',
            'journalentry show',
            'journalentry edit',
            'journalentry delete',
            'report sales',
            'report receivables',
            'report payables',
            'product&service manage',
            'product&service create',
            'product&service edit',
            'product&service delete',
            'product&service import',
            'unit manage',
            'unit cerate',
            'unit edit',
            'unit delete',
            'tax manage',
            'tax create',
            'tax edit',
            'tax delete',
            'category manage',
            'category create',
            'category edit',
            'category delete',
            'pos manage',
            'pos show',
            'pos dashboard manage',
            'pos add manage',
            'pos cart manage',
            'warehouse manage',
            'warehouse create',
            'warehouse edit',
            'warehouse delete',
            'warehouse show',
            'warehouse import',
            'purchase manage',
            'purchase create',
            'purchase edit',
            'purchase delete',
            'purchase show',
            'purchase send',
            'purchase payment create',
            'purchase payment delete',
            'purchase product delete',
            'report warehouse',
            'report purchase',
            'report pos',
            'report pos vs expense',
            'crm manage',
            'crm dashboard manage',
            'crm setup manage',
            'crm report manage',
            'lead manage',
            'lead create',
            'lead edit',
            'lead delete',
            'lead show',
            'lead move',
            'lead import',
            'lead call create',
            'lead call edit',
            'lead call delete',
            'lead email create',
            'lead to deal convert',
            'lead report',
            'deal report',
            'deal manage',
            'deal create',
            'deal edit',
            'deal delete',
            'deal show',
            'deal move',
            'deal import',
            'deal task create',
            'deal task edit',
            'deal task delete',
            'deal task show',
            'deal call create',
            'deal call edit',
            'deal call delete',
            'deal email create',
            'pipeline manage',
            'pipeline create',
            'pipeline edit',
            'pipeline delete',
            'dealstages manage',
            'dealstages create',
            'dealstages edit',
            'dealstages delete',
            'leadstages manage',
            'leadstages create',
            'leadstages edit',
            'leadstages delete',
            'labels manage',
            'labels create',
            'labels edit',
            'labels delete',
            'source manage',
            'source create',
            'source edit',
            'source delete',
            'lead task create',
            'lead task edit',
            'lead task delete',
        ];

        foreach ($permissions as $permissionName) {
            // Create permission if it doesn't exist
            $permission = Permission::firstOrCreate(['name' => $permissionName, 'guard_name' => 'web']);
            // Assign permission to the role
            if (!$role->hasPermissionTo($permission)) {
                $role->givePermissionTo($permission);
            }
        }

        User::CompanySetting($accountant->id);

        $modules = [
            'Account',
            'ProductService',
            'Hrm',
            'Lead',
            'Pos',
            'Stripe',
            'Taskly',
            'Paypal',
            'DoubleEntry',
        ];

        foreach ($modules as $module) {
            // Create active module entry
            $activeModule = userActiveModule::firstOrCreate(['module' => $module, 'user_id' => $accountant->id]);
        }

    }
}